variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build

build-win10-optix:
  stage: build
  tags:
    - win10-optix
  before_script:
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/VC/Auxiliary/Build/vcvars64.bat
  script:
    - mkdir bla
    - cd bla
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/VC/Auxiliary/Build/vcvars64.bat
    - c:/"Program Files"/CMake/bin/cmake.exe ..
    - devenv.com /build Debug Optix-OWL.sln
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/Common7/IDE/devenv.com /clean
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/Common7/IDE/devenv.com /build Debug Optix-OWL.sln
    - devenv.exe /build Debug Optix-OWL.sln

build-ubuntu18-release:
  stage: build
  tags:
    - ubuntu18-optix
  script:
    - mkdir bin_release
    - cd bin_release
    - export PATH=$PATH:/usr/local/cuda/bin
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DOptiX_INSTALL_DIR=/usr/local/NVIDIA-OptiX-SDK-7.0.0-linux64
    - make

build-ubuntu18-debug:
  stage: build
  tags:
    - ubuntu18-optix
  script:
    - mkdir bin_debug
    - cd bin_debug
    - export PATH=$PATH:/usr/local/cuda/bin
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DOptiX_INSTALL_DIR=/usr/local/NVIDIA-OptiX-SDK-7.0.0-linux64
    - make

