
stages:
  - build

build:
  stage: build
  tags:
    - win10-optix
  script:
    - mkdir bla
    - cd bla
    - c:/"Program Files"/CMake/bin/cmake.exe ..
    - C:/Program\ Files\ (x86)/Microsoft\ Visual\ Studio/2019/Community/Common7/Tools/VsDevCmd.bat
    - devenv /build Debug Optix-OWL.sln

