variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build

build:
  stage: build
  tags:
    - win10-optix
  script:
    - mkdir bla
    - cd bla
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/VC/Auxiliary/Build/vcvars64.bat
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/Common7/Tools/VsDevCmd.bat
    - c:/"Program Files"/CMake/bin/cmake.exe ..
    - devenv /clean
    - devenv /build Debug Optix-OWL.sln
    - C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/Community/Common7/IDE/devenv.exe /build Debug Optix-OWL.sln

